# Naming recipe: Moflux canopy receiver
#
# Your files look like:  SEPT310a.21.obs  (15 dig)

name: moflux_canopy
description: Missouri Ozark forest, canopy receiver

site: MOZ
agency: CAL
receiver_number: 1
receiver_type: canopy
sampling: "15S"
period: "1H"
content: AA
file_type: rnx

layout: yyddd_subdirs
glob: "*.obs"

fields:
  - skip: 4           # SEPT
  - doy: 3            # 001
  - hour_letter: 1    # a
  - skip: 1           # .
  - yy: 2             # 25
  - skip: 1           # .
  - skip: 3           # obs
