# Naming recipe: Rosalia reference receiver
#
# Your files look like:  rref001a15.25o
#                         ····^^^·^^_^^·
#                         skip doy |mn . yy skip
#                              hour_letter
#
# Known fields: year(4), yy(2), doy(3), month(2), day(2),
#               hour(2), minute(2), hour_letter(1), skip(N)

name: rosalia_reference
description: Rosalia forest, reference receiver, Septentrio PolaRx5

site: ROS
agency: TUW
receiver_number: 1
receiver_type: reference
sampling: "05S"
period: "15M"
content: AA
file_type: rnx

layout: yyddd_subdirs
glob: "*.??o"

fields:
  - skip: 4           # rref
  - doy: 3            # 001
  - hour_letter: 1    # a
  - minute: 2         # 15
  - skip: 1           # .
  - yy: 2             # 25
  - skip: 1           # o
