"""canvod.ops — Preprocessing operations pipeline for GNSS VOD data."""

__version__ = "0.1.0"

from canvod.ops.base import Op, OpResult
from canvod.ops.grid import GridAssignment, grid_assign
from canvod.ops.pipeline import Pipeline, PipelineResult
from canvod.ops.registry import build_default_pipeline, build_statistics_pipeline
from canvod.ops.statistics import (
    AccumulatorSet,
    AnomalyClassification,
    AnomalyTimeline,
    BivariateHistogram,
    BOCPDAccumulator,
    BOCPDResult,
    CARResult,
    CellSignalKey,
    ChangepointStatus,
    CircularAccumulator,
    ClimatologyGrid,
    ClimatologyHeatmap,
    ConfidenceEnvelope,
    DFAResult,
    EMDResult,
    EWMAAccumulator,
    FadingAccumulator,
    GaussianMixtureResult,
    GKSketch,
    GoertzelAccumulator,
    HuberRLS,
    IncrementalPCA,
    LombScargleResult,
    MultitaperResult,
    MutualInformationResult,
    PermutationEntropyAccumulator,
    ProfileRegistry,
    QualityFlag,
    RecursiveLeastSquares,
    RunningMedianFilter,
    S4Accumulator,
    SampleEntropyResult,
    SiderealFilterResult,
    SpectralSlopeAccumulator,
    SSAResult,
    StatisticsQuery,
    StatisticsSnapshot,
    StatisticsStore,
    StreamingAutocovariance,
    StreamingHistogram,
    TransferEntropyResult,
    UpdateStatistics,
    VariableStats,
    WelfordAccumulator,
    adjacency_from_grid,
    aggregation_uncertainty,
    anomaly_zscore,
    anomaly_zscore_batch,
    car_smooth,
    classify_anomaly,
    classify_anomaly_batch,
    conditional_entropy,
    dfa,
    effective_sample_size,
    emd_decompose,
    fit_gaussian_mixture,
    fit_gaussian_mixture_from_histogram,
    hurst_exponent,
    icar_smooth,
    joint_entropy,
    lomb_scargle,
    mad,
    multitaper_psd,
    mutual_information,
    mutual_information_from_histogram,
    robust_std,
    sample_entropy,
    shannon_entropy,
    shannon_entropy_from_histogram,
    sidereal_filter,
    sigma_cn0,
    sigma_delta_snr,
    sigma_transmissivity,
    sigma_vod,
    ssa_decompose,
    transfer_entropy,
    trimmed_mean,
    update_statistics,
)
from canvod.ops.temporal import TemporalAggregate, temporal_aggregate
