name: Platform Tests

on: [push, pull_request]

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
    build:
        name: Tests • ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: '3.14'
                      name: 'Python 3.14 - Ubuntu'
                    - os: windows-latest
                      python-version: '3.14'
                      name: 'Python 3.14 - Windows'
                    - os: macos-latest
                      python-version: '3.14'
                      name: 'Python 3.14 - macOS'

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v6
            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true
            - name: Set up Python
              run: uv python install
            - name: Install just
              run: |
                  if [[ "${{ runner.os }}" == "Linux" ]]; then
                    sudo apt-get update
                    sudo apt-get install -y just
                  elif [[ "${{ runner.os }}" == "macOS" ]]; then
                    brew update
                    brew install just
                  elif [[ "${{ runner.os }}" == "Windows" ]]; then
                    choco install just -y
                  else
                    echo "Unsupported OS for just install: ${{ runner.os }}"
                    exit 1
                  fi
            - name: Install the Project
              run: uv sync --locked --dev
            - name: Run Tests
              run: just test-all-packages
