name: Platform Tests 🐍🐧🍎

on: [push, pull_request]

jobs:
    build:
        name: Tests • ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: '3.13'
                      name: '🐍 3.13 • 🐧 Ubuntu'
                    - os: ubuntu-latest
                      python-version: '3.14'
                      name: '🐍 3.14 • 🐧 Ubuntu'
                    - os: windows-latest # Note: 'aux' package may have issues
                      python-version: '3.13'
                      name: "🐍 3.13 • 🪟 Windows"
                    - os: windows-latest
                      python-version: '3.14'
                      name: "🐍 3.14 • 🪟 Windows"
                    - os: macos-latest
                      python-version: '3.13'
                      name: '🐍 3.13 • 🍎 macOS'
                    - os: macos-latest
                      python-version: '3.14'
                      name: '🐍 3.14 • 🍎 macOS'

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v4
            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v6
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true
            - name: Set up Python
              run: uv python install
            - name: Install just
              uses: extractions/setup-just@v2
            - name: Install the Project
              run: uv sync --locked --dev
            - name: Run Tests
              run: just test-all-packages
